# Generated by Django 3.1 on 2020-08-22 04:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('num_posts', models.IntegerField(default=0)),
                ('num_followers', models.IntegerField(default=0)),
                ('num_following', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('full_caption', models.TextField(blank=True)),
                ('short_caption', models.TextField(blank=True)),
                ('mentions', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('song', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('thumbnail', models.URLField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.user')),
            ],
        ),
    ]
