# Generated by Django 3.1 on 2020-08-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200823_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
